spring.application.name=TrackCalServer
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}

jwt.expiration=86400000

app.registration-otp.expiration-minutes=10
app.registration-otp.resend-cooldown-seconds=60

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
